Zack/inventory
ucladevx/BruinBot-Frontend pull request #17
Opened 2020-11-29 23:53 UTC by Zhirschhorn

I created two new screens:
-InventoryModificationScreen: This basically just takes the InventoryView component and adds an Add Item button at the bottom. Related to this, I also changed the InventoryView to take a new prop called collapsible. When set to false, the inventory view will start full screen and will no be able to be swiped down. It is an optional prop that defaults to true so it will not break previous code.

-Add Item Screen: This is where I spent most of my time. I used expo Camera (https://docs.expo.io/versions/latest/sdk/camera/) and expo ImagePicker (https://docs.expo.io/versions/latest/sdk/imagepicker/) to implement the images. When a picture is taken/chosen, the camera is replaced with that image. I used React Native Elements' Input for the inputs underneath. It checks the cost and quantity inputs and will show an error/not submit if they are not proper input. 

This is my first time writing react code so I'm sure there will be a lot of issues, lmk and I'll be happy to fix them

Notion: https://www.notion.so/BruinBot-Inventory-Modification-Forms-c197d855843e421b867bde043a1eef9a

![AddItemWithPicture](https://user-images.githubusercontent.com/13991762/100556959-b892b580-325a-11eb-9e4e-d7f04050b7ce.png)
![AddItemCamera](https://user-images.githubusercontent.com/13991762/100556964-bd576980-325a-11eb-8944-d813970807f2.png)
![InventoryModification](https://user-images.githubusercontent.com/13991762/100556970-c1838700-325a-11eb-9cf7-9407ac5916aa.png)

2020-12-02 20:35 UTC, zhang-edward commented
I messed up the GitHub actions so it didn't catch this, but you should run Prettier to fix formatting errors! `npm lint:fix`

2020-12-03 06:42 UTC, zhang-edward requested changes
See above comment about running `npm lint:fix` and fixing those errors!

2020-12-03 06:42 UTC, zhang-edward commented on src/containers/AddItemScreen.tsx
> +        if (pic.cancelled){
nitpick
```suggestion
     setPhoto(pic.cancelled ? null : pic.uri)
```

2020-12-03 06:42 UTC, zhang-edward commented on src/containers/AddItemScreen.tsx
> +    if (hasPermission === false) {
nitpick
```suggestion
    else if (hasPermission === false) {
```

2020-12-03 06:42 UTC, zhang-edward commented on src/containers/InventoryModification.tsx
> +    navigation: any;
Again, don't use `any` here

2020-12-03 06:42 UTC, zhang-edward commented on src/containers/InventoryModification.tsx
> +			<TouchableOpacity style={styles.button} onPress={() => {
Could we use the React Native Elements button here instead?
https://reactnativeelements.com/docs/button/

2020-12-03 06:42 UTC, zhang-edward commented on src/containers/AddItemScreen.tsx
> +            <Ionicons name="ios-photos" style={{
I would recommend using icons from React Native Elements and choosing a consistent icon set (I think we're just sticking to FontAwesome for now)

https://reactnativeelements.com/docs/icon
Icon name: https://fontawesome.com/icons?d=gallery

2020-12-03 06:42 UTC, zhang-edward commented on src/containers/AddItemScreen.tsx
> +            <FontAwesome name="circle" style={{
See above comment

2020-12-03 06:42 UTC, zhang-edward commented on src/containers/AddItemScreen.tsx
> +                <FontAwesome name="times" style={
Same thing here

2020-12-03 06:42 UTC, zhang-edward commented on src/containers/InventoryModification.tsx
> +    const [infor, setInfor] = useState(botInfo);
Nitpick but could we call this `info` instead?

Also, introducing an underscore before variable names will fix the warning about unused vars, if we aren't using for now but are planning to in the future.

```suggestion
    const [info, _setInfo] = useState(botInfo);
```

2020-12-08 03:21 UTC, zhang-edward approved these changes

2020-12-08 03:22 UTC, zhang-edward commented
Let's fix these merge conflicts too. 

For the package files, just pull main and then just regenerate the `package-lock.json` and `package.json` files!

2020-12-08 03:41 UTC, Zhirschhorn commented
> Let's fix these merge conflicts too.
> 
> For the package files, just pull main and then just regenerate the `package-lock.json` and `package.json` files!

How do I regenerate the 'package-lock.json' and 'package.json' files?

2020-12-08 03:43 UTC, Zhirschhorn commented
> Let's fix these merge conflicts too.
> 
> For the package files, just pull main and then just regenerate the `package-lock.json` and `package.json` files!

2020-12-08 03:43 UTC, Zhirschhorn commented
Also I accidently

2020-12-09 04:40 UTC, dvorjackz commented
> > Let's fix these merge conflicts too.
> > For the package files, just pull main and then just regenerate the `package-lock.json` and `package.json` files!
> 
> How do I regenerate the 'package-lock.json' and 'package.json' files?

1. Fix the merge conflict in package.json and app.tsx. Basically go to main, pull in the changes, then `git merge main` on your branch. Looks like to fix the merge conflicts, you just need to include both your changes and the incoming changes from main.
2. Delete package-lock.json and `npm i`
3. Complete the merge by adding all three files and committing

2020-12-09 10:20 UTC, merged