Cleaned up ItemCatalogue UI and linked to backend
ucladevx/BruinBot-Frontend pull request #37
Opened 2020-12-18 08:11 UTC by Saagar3690

### **Changes**
1. Updated Item Catalogue UI to use the MapMenuView component to display items
2. Connected to backend, so items now display for a bot given by bot id (passed through props)
3. Modified MapMenuView to have an additional optional prop called clickable, which indicates if each item card can be pressed (this is for when I implement navigation to payment screen)
4. ItemCatalogueService provides two async functions with requests to backend
   - GET request to bots/bot for a bot given by bot id
   - PUT request to addItem with body botId, itemId, and quantity (this will be used for modifying inventory which I haven't done yet)

### **In Action**
![RPReplay_Final1608277212](https://user-images.githubusercontent.com/30224372/102590458-788a5a00-40c5-11eb-9073-e7997dfca6e2.gif)
iOS
![IMG_5424](https://user-images.githubusercontent.com/30224372/102588740-c8b3ed00-40c2-11eb-8bc3-a9cc0ffc7647.PNG)
Android
<img width="403" alt="Screen Shot 2020-12-17 at 11 39 34 PM" src="https://user-images.githubusercontent.com/30224372/102588803-dec1ad80-40c2-11eb-88a5-ac2aebf80cb4.png">

### **TODO (in order of priority)**
1. Navigate to Payment screen after clicking an item
2. Send request to backend for payment screen to modify inventory
3. Sale statistics 
4. Implement sorting feature to sort items by price, name ascending/descending

2020-12-18 20:12 UTC, dvorjackz requested changes
Taking an exam rn, but without looking at the code yet, could you show the quantity of each item? Also, make sure to merge in the latest main.

2020-12-19 07:48 UTC, Saagar3690 reviewed
### **Changes**
1. Added quantity field to each item (if quantity is 0 it displays sold out in bold and red as shown below)
2. Linked item to payment stubs page - when you press an items, it takes you to the payment page
   - passes in the item _id, amount (i.e price) which will be needed for Stripe API payment processing, and quantity (which for now is a hardcoded -1 since item count reduces in inventory)
3. Payment Stubs page now sends a request to the backend to update inventory (you can see below the count was 253 to 250 to 247)

### **In Action**
**Item with quantity > 0**
![IMG_5428](https://user-images.githubusercontent.com/30224372/102684120-bdc48f80-418a-11eb-86ba-2cc4bbfc6d00.PNG)
**Sold Out**
![IMG_5427](https://user-images.githubusercontent.com/30224372/102684121-be5d2600-418a-11eb-9f7a-87609ecdc618.PNG)
**In Action Video**
https://user-images.githubusercontent.com/30224372/102684118-b9987200-418a-11eb-9c1b-8b5c2c4fa6e8.mp4
**Response from backend after updating inventory**
![Screen Shot 2020-12-18 at 11 31 21 PM](https://user-images.githubusercontent.com/30224372/102684114-ad141980-418a-11eb-836b-8596c5510fe4.png)
**Proof of quantity changing**
![IMG_5431](https://user-images.githubusercontent.com/30224372/102684122-bef5bc80-418a-11eb-966e-6ccb74412d83.PNG)

### **TODO (by priority) **
1. Sale Statistics
2. Sort items by price, name, etc.
3. Anything else??

2021-01-03 21:00 UTC, zhang-edward approved these changes

2021-01-11 20:48 UTC, zhang-edward approved these changes
Left a few nitpick comments but otherwise looks fine

2021-01-11 20:48 UTC, zhang-edward commented on src/containers/PaymentInfo.tsx
> +	const [botId] = useState<string>(
I don't think `useState` is necessary here

```suggestion
	const botId = 
```

2021-01-11 20:48 UTC, zhang-edward commented on src/containers/PaymentInfo.tsx
> +		route.params.botId ? route.params.botId : '5ff798be0390ab19822d21db'
```suggestion
		route.params.botId ?? '5ff798be0390ab19822d21db'
```

2021-01-12 20:59 UTC, merged