Map code refactoring
ucladevx/BruinBot-Frontend pull request #49
Opened 2021-01-03 20:22 UTC by zhang-edward

Refactored the props so that `MapMenuHeader` only takes in the data it needs to render.

Map functionality should be identical.

2021-01-03 23:18 UTC, dvorjackz approved these changes
One typescript warning

2021-01-06 22:24 UTC, thilan-tran approved these changes
LGTM!

2021-01-07 01:22 UTC, dvorjackz requested changes
Merge errors again

2021-01-07 01:22 UTC, dvorjackz commented on src/containers/DashboardScreen.tsx
> +						onPress={() => navigation.navigate('InventoryModification')}
Can we keep one of them linked to map so that we can easily get to it

2021-01-07 01:22 UTC, dvorjackz commented on src/containers/MapScreen.tsx
> +const EVENT_ID = '5ff10da1af6f951a7719ca96';
Use the event id from the config.ts

2021-01-07 01:22 UTC, dvorjackz commented on src/containers/MapScreen.tsx
> +			const data = await BotService.getEventBots(EVENT_ID);
^

2021-01-07 01:22 UTC, dvorjackz commented on src/containers/MapScreen.tsx
> -			const { mapPaths } = formatMapPathsData(await MapService.getMapPaths());
Why is this being removed?

2021-01-07 01:22 UTC, dvorjackz commented on src/containers/MapScreen.tsx
> -			setBotPaths(mapPaths);
^

2021-01-07 01:22 UTC, dvorjackz commented on src/containers/MapScreen.tsx
> -	const [botPaths, setBotPaths] = useState<Location[][] | null>(null);
Why is botPaths being changed?

2021-01-07 01:22 UTC, dvorjackz commented on src/containers/MapScreen.tsx
> +						lineCoords={botPaths ? Object.values(botPaths) : []}
Revert

2021-01-07 01:22 UTC, dvorjackz commented on src/containers/MapScreen.tsx
> -	const botPaths: Location[][] = [];
Revert

2021-01-07 01:22 UTC, dvorjackz commented on src/containers/MapScreen.tsx
> +		botPaths[bot._id] = bot.path;
Revert

2021-01-07 01:22 UTC, dvorjackz commented on src/containers/MapScreen.tsx
> +	return { botMarkers, botHeaderInfo, botItems, botPaths };
Revert

2021-01-07 01:22 UTC, dvorjackz commented on src/containers/MapScreen.tsx
> -	return { mapPaths };
Revert

2021-01-11 22:13 UTC, zhang-edward commented
@dvorjackz Can you double check that I didn't accidentally delete your bot paths code, as far as I can tell it's all there

2021-02-22 23:35 UTC, zhang-edward commented
this is ancient

2021-02-22 23:35 UTC, closed without merging