Reorganized files
ucladevx/BruinBot-Frontend pull request #50
Opened 2021-01-06 22:37 UTC by zhang-edward

## Why?
In order to keep different groups of components _compartmentalized in their own folders_.
Ideally, the `components` folder is for _generic React components_ that we reuse in multiple places.

## How do we organize our files now?
Each folder within `containers` should encapsulate some particular user flow; this could mean one specific screen in the app.

The components that are used across multiple screens, such as `Loading.tsx`, are placed into `components`. 

## Examples
Each component (and TS interface definitions) for the map screen now resides in the `Map` folder in `containers`. (We should use PascalCase to name folders within 'containers' to be consistent with file names) 

In the future, if we decide to use our `MapComponent` across several different screens (requiring it to be made into a generic component), we would move it into the `components` folder.

![image](https://user-images.githubusercontent.com/12520186/103826871-9136c180-502c-11eb-82b5-2c5c6a3f41dd.png)

2021-01-07 01:48 UTC, dvorjackz commented
Some ts errors, you can catch em with `npx tsc`

2021-01-07 01:49 UTC, dvorjackz requested changes
Tsc warnings

2021-01-07 01:59 UTC, zhang-edward commented
Apparently git will not recognize renaming folders from lowercase to uppercase so u gotta do some fiddly stuff to get that to work

2021-01-08 05:05 UTC, dvorjackz approved these changes

2021-02-09 04:58 UTC, merged