Navigate to Weight Screen after Add Item Screen
ucladevx/BruinBot-Frontend pull request #67
Opened 2021-01-30 22:51 UTC by Zhirschhorn

**Description**
-App.tsx: Added ItemWeight Screen to the stack (added a botId prop so it can navigate back to the correct bots inventory modification when done)
-AddItemScreen: navigave to ItemWeight after adding itme
-ItemWeightScreen: changed to rotue parameters, added botId param, changed baseURL, navigate to Inventory Modification when done 
-ItemService: return item object that is added

**Screenshots**
Nothing visual was changed

**Notion**
https://www.notion.so/Navigate-from-add-item-screen-to-weight-screen-0a1748ece9e14353a6623ddef5b2686e

2021-02-01 03:59 UTC, Saagar3690 requested changes
Looks good for the most part. The only change is to use Bot in navigation instead of botId, since we want to keep it consistent. All my comments are pertaining that minor change, everything else seems solid.

2021-02-01 03:59 UTC, Saagar3690 commented on App.tsx
> +		botId: string;
I think we want to keep it consistent right, so instead of botId, we should pass in Bot

2021-02-01 03:59 UTC, Saagar3690 commented on src/containers/AddItemScreen.tsx
> +					botId: bot._id,
with previous comment, pass by Bot instead of botId for consistency

2021-02-01 03:59 UTC, Saagar3690 commented on src/containers/ItemWeightScreen.tsx
> +				let bot: Bot = await BotService.getOneBot(route.params.botId);
should be able to remove this call once we make it pass bot instead of botId

2021-02-01 23:34 UTC, Zhirschhorn commented
@Saagar3690 changed. Thanks for the review!

2021-02-03 05:17 UTC, Saagar3690 approved these changes

2021-02-06 21:09 UTC, merged